name: 'supply_chain_analytics'
version: '1.0.0'
config-version: 2

# Project profile
profile: 'supply_chain_analytics'

# Directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Output directory
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  supply_chain_analytics:
    # Staging models
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate models
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      
    # Mart models
    marts:
      +materialized: table
      +schema: marts
      +tags: ["analytics", "kpi"]

# Seeds configuration
seeds:
  supply_chain_analytics:
    +schema: seeds

# Tests
tests:
  supply_chain_analytics:
    +store_failures: true
    +schema: test_results

# Documentation
docs-paths: ["docs"]
