supply_chain_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: supply_chain_analytics
      schema: public
      threads: 4
      keepalives_idle: 0
    
    prod:
      type: postgres
      host: production-db.example.com
      port: 5432
      user: analytics_user
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      dbname: supply_chain_analytics_prod
      schema: public
      threads: 8
      keepalives_idle: 0
